# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kcg < Formula
  desc "kumak1 Convenient Git tools."
  homepage "https://github.com/kumak1/kcg"
  version "0.13.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kumak1/kcg/releases/download/v0.13.1/kcg_0.13.1_darwin_arm64.tar.gz"
      sha256 "c7a106e2664e3ea025974506f5b674e0effb5ec29f302628be6f5b6d99c5e7af"

      def install
        bin.install Dir['kcg']
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kumak1/kcg/releases/download/v0.13.1/kcg_0.13.1_darwin_amd64.tar.gz"
      sha256 "0942302efcceeb544030ed373d0a7034af4a313db086b5d161a556ce969d519f"

      def install
        bin.install Dir['kcg']
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumak1/kcg/releases/download/v0.13.1/kcg_0.13.1_linux_arm64.tar.gz"
      sha256 "dcdf7317927bdca6dd64c66a6b5632a751509689c7dd71a6482f255a24f32123"

      def install
        bin.install Dir['kcg']
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kumak1/kcg/releases/download/v0.13.1/kcg_0.13.1_linux_amd64.tar.gz"
      sha256 "707011fbf647fd19760dd9da0698406df3e4b225fed49a4c0fcafd9ec9de86ca"

      def install
        bin.install Dir['kcg']
      end
    end
  end

  test do
    system "#{bin}/kcg"
  end
end
