# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kcg < Formula
  desc "kumak1 Convenient Git tools."
  homepage "https://github.com/kumak1/kcg"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kumak1/kcg/releases/download/0.4.0/kcg_0.4.0_darwin_arm64.tar.gz"
      sha256 "bb903484294583a575a0a7d92e2bcb1bf637f4be77517d5487e6ad3c562cf4d6"

      def install
        bin.install Dir['kcg']
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kumak1/kcg/releases/download/0.4.0/kcg_0.4.0_darwin_amd64.tar.gz"
      sha256 "da1d7e9cca13075241240b8fa82c778b864c2c0efac4bf179d9e22308b08898f"

      def install
        bin.install Dir['kcg']
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumak1/kcg/releases/download/0.4.0/kcg_0.4.0_linux_arm64.tar.gz"
      sha256 "d00d1f0a89d6f5fcb8a4fad2a346ef5f7aa359f12ce2a0c0612098686a9f3f1c"

      def install
        bin.install Dir['kcg']
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kumak1/kcg/releases/download/0.4.0/kcg_0.4.0_linux_amd64.tar.gz"
      sha256 "55ccf3262d5e6c6d19c42ad37a6c6b50d797a4e32af912cd4663e7f8a1912c0c"

      def install
        bin.install Dir['kcg']
      end
    end
  end

  test do
    system "#{bin}/kcg"
  end
end
